routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);
Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);
Route::post('/blog/{post}/comments', [
    'uses' => 'BlogController@comments',
    'as' => 'blog.comments'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);
Route::get('/author/{user}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);
Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit')->name('edit.account');
Route::put('/edit-account/', 'Backend\HomeController@update')->name('update.account');

Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('blog', 'BlogController');
    Route::post('blog/restore/{id}', [
        'uses' => 'BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('blog/force-destroy/{id}', [
        'uses' => 'BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
});
Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController', ['except' => 'destroy']);
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy'
    ]);
    Route::get('users/{user}', [
        'as' => 'users.confirm',
        'uses' => 'UserController@confirm'
    ]);
});

Route::get('/tags',function (){
    $tags = App\Tag::pluck('name');
    return $tags;
});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use function GuzzleHttp\Psr7\str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'view_count', 'image'];
    protected $dates = ['published_at', 'created_at', 'updated_at'];
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];

        foreach ($tags as $tag) {
            $newTag = Tag::firstOrCreate(
                ['slug' => str_slug($tag), 'name' => ucwords(trim($tag))]
            );
            $newTag->save();

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }

    // Relationships
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    // Accessors- Mutators
    public function getImageUrlAttribute($image)
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $this->image;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $this->image);
            }
        }
        return $imageUrl;
    }

    public function getDateAttribute()
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getImageThumbUrlAttribute()
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            // lấy extension = cách tìm dấu . cuối cùng trong tên image và lấy từ sau dấu chấm đến hết
            $extenstion = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".$extenstion", "_thumb.$extenstion", $this->image);
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $thumbnail;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $thumbnail);
            }
        }
        return $imageUrl;
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function getTagsHtmlAttribute()
    {
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = '<a href="' . route('tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(', ', $anchors);
    }

    public function commentsNumber()
    {
        $commentsNumber = $this->comments->count();
        return $commentsNumber . ' ' . str_plural('Comment', $commentsNumber);
    }

    public function setPublishedAtAttribute($value)
    {
        if ($value) {
            $value = date("Y-m-d H:i:s", strtotime($value));
        }
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if ($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel()
    {
        if (!$this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    // Scope
    public function scopeMoiNhat($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where("published_at", "<=", Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    // Get list Tháng - Năm - Số lượng Post
    public static function archives()
    {
        return static::selectRaw('count(id) post_count, YEAR(published_at) year, MONTHNAME(published_at) month')->published()->groupBy('year', 'month')->orderBy('published_at', 'desc')->get();
    }

    // check if user searched
    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }
        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereYear('published_at', $year);
        }

        if (isset($filter['term']) && $term = $filter['term']) {
            $query->where(function ($q) use ($term) {
                $q->whereHas('user', function ($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function ($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{

    protected $limit = 3;
    protected $uploadPath;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permission');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\CreatePostRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = config('cms.image.directory');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = false;
        if (($status = $request->get('status')) && $status == 'trash') {
            $posts = Post::onlyTrashed()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
            $onlyTrashed = true;
        } elseif (($status = $request->get('status')) && $status == 'published') {
            $posts = Post::published()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'scheduled') {
            $posts = Post::scheduled()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'draft') {
            $posts = Post::draft()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'own') {
            $posts = $request->user()->posts()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } else {
            $posts = Post::with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        }
        $statusList = $this->statusList($request);
        return view('backend.blog.index', compact('posts', 'onlyTrashed', 'statusList'));
    }

    private function statusList($request)
    {
        return [
            'own' => $request->user()->posts()->count(),
            'all' => Post::count(),
            'published' => Post::published()->count(),
            'scheduled' => Post::scheduled()->count(),
            'draft' => Post::draft()->count(),
            'trash' => Post::onlyTrashed()->count()
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.create', compact('post', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $data = $this->handleRequest($request);
        $newPost = $request->user()->posts()->create($data);
        if ($newPost) {
            $newPost->createTags($data["post_tags"]);
            Session::flash('success', 'Tạo mới thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Tạo mới thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    private function handleRequest($request)
    {
        $request->request->add(['view_count' => 0]);
        $data = $request->all();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $time = time();
            $fileName = $time . $fileName;
            $destination = $this->uploadPath;
            $successUploaded = $image->move($destination, $fileName);
            // Create thumb image
            if ($successUploaded) {
                $width = config('cms.image.thumbnail.width');
                $height = config('cms.image.thumbnail.height');
                $extension = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$extension}", "_thumb.{$extension}", $fileName);

                Image::make($destination . '/' . $fileName)
                    ->resize($width, $height)
                    ->save($destination . '/' . $thumbnail);
            }
            // end Create thumb image
            $data['image'] = $fileName;
        }
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreatePostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        $oldImage = $post->image;
        $data = $this->handleRequest($request);
        $updated = $post->update($data);

        if ($updated) {
            $post->createTags($data['post_tags']);
            if ($oldImage != $post->image) {
                $this->removeImage($oldImage);
            }
            Session::flash('success', 'Sửa thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Sửa thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id)->delete();
        if ($post) {
            return redirect()->back()->with('trash-message', ['Xóa post thành công', $id]);
        } else {
            return redirect()->back()->with('fail', 'Xóa post thất bại');
        }
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->find($id)->restore();
        if ($post) {
            return redirect()->back()->with('success', 'Undo post thành công');
        } else {
            return redirect()->back()->with('fail', 'Undo post thất bại');
        }
    }

    public function forceDestroy($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $image = $post->image;
        $deletePost = $post->forceDelete();

        if ($deletePost) {
            $this->removeImage($image);
            return redirect()->back()->with('success', 'Xóa thành công');
        } else {
            return redirect()->back()->with('fail', 'Xóa thất bại');
        }
    }

    public function removeImage($image)
    {
        if (!empty($image)) {
            $imagePath = $this->uploadPath . '/' . $image;
            $ext = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $image);
            $thumbnailPath = $this->uploadPath . '/' . $thumbnail;
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
            if (file_exists($thumbnailPath)) {
                unlink($thumbnailPath);
            }
        }
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AccountUpdateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('backend.home.index');
    }

    public function edit(Request $request)
    {
        $user = $request->user();
        return view('backend.home.edit',compact('user'));
    }

    public function update(AccountUpdateRequest $request)
    {
        $user = $request->user();
        $update = $user->update($request->all());
        if($update){
            return redirect()->back()->with('success','Account was updated successfully');
        } else {
            return redirect()->back()->with('fail','Account was updated fail');
        }
    }
}

resources/views/backend/blog/create.blade.php
@extends('layouts.backend.main')
@section('title','MyBlog | Dashboar')
@section('link')
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="{{asset('/backend/plugins/tag-editor/jquery.tag-editor.css')}}">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Blog
                <small>Add new post</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.blog.index')}}">Blog</a></li>
                <li class="active">Add new Post</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {!! Form::open([
                'method'=>'POST',
                'route'=>'backend.blog.store',
                'files'=>TRUE,
                'id'=>'post-form'
                ]) !!}
                @include('backend.blog.form')
                {!! Form::close() !!}
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection
@include('backend.blog.script')

resources/views/backend/blog/edit.blade.php
@extends('layouts.backend.main')
@section('title','MyBlog | Dashboar')
@section('link')
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="{{asset('/backend/plugins/tag-editor/jquery.tag-editor.css')}}">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Blog
                <small>Edit post</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.blog.index')}}">Blog</a></li>
                <li class="active">Edit Post</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {!! Form::model($post,[
                'method'=>'PUT',
                'route'=>['backend.blog.update',$post->id],
                'files'=>TRUE,
                'id'=>'post-form'
                ]) !!}
                @include('backend.blog.form')
                {!! Form::close() !!}
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection
@include('backend.blog.script')

resources/views/backend/blog/form.blade.php
<div class="col-xs-9">
    <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                {!! Form::label('title') !!}
                {!! Form::text('title',null,['class'=>'form-control']) !!}
                @if($errors->has('title'))
                    <span class="help-block">{{$errors->first('title')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('excerpt') ? 'has-error' : '' }}">
                {!! Form::label('excerpt') !!}
                {!! Form::textarea('excerpt',null,['class'=>'form-control']) !!}
                @if($errors->has('excerpt'))
                    <span class="help-block">{{$errors->first('excerpt')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
                {!! Form::label('body') !!}
                {!! Form::textarea('body',null,['class'=>'form-control']) !!}
                @if($errors->has('body'))
                    <span class="help-block">{{$errors->first('body')}}</span>
                @endif
            </div>

        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>
<div class="col-xs-3">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Publish</h3>
        </div>
        <div class="box-body">
            <div class="form-group {{ $errors->has('published_at') ? 'has-error' : '' }}">
                {!! Form::label('published_at','Published Date') !!}
                {!! Form::text('published_at',null,['class'=>'form-control']) !!}
                @if($errors->has('published_at'))
                    <span class="help-block">{{$errors->first('published_at')}}</span>
                @endif
            </div>
        </div>
        <div class="box-footer">
            <div class="pull-left">
                <a id="draft-btn" href="" class="btn btn-default">Save draft</a>
            </div>
            <div class="pull-right">
                {!! Form::submit('Publish',['class'=>'btn btn-success']) !!}
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Category</h3>
        </div>
        <div class="box-body">
            <div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
                {!! Form::select('category_id',$categories,null,['class'=>'form-control','placeholder'=>'Choose your category']) !!}
                @if($errors->has('category_id'))
                    <span class="help-block">{{$errors->first('category_id')}}</span>
                @endif
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Feature Image</h3>
        </div>
        <div class="box-body text-center">
            <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                {!! Form::label('image','Image') !!}
                <div class="fileinput-new img-thumbnail" style="width: 200px; height: 150px;">
                    <img style="width: 100%;height: 100%;" src="{{($post->image_thumb_url) ? $post->image_thumb_url : 'https://place-hold.it/200x150'}}"
                         alt="...">
                </div>
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="fileinput-preview fileinput-exists img-thumbnail"
                         style="max-width: 200px; max-height: 150px;">
                    </div>
                    <div>
                                        <span class="btn btn-outline-secondary btn-file"><span class="fileinput-new">Select image</span><span
                                                class="fileinput-exists">Change</span>{!! Form::file('image') !!}</span>
                        <a href="#" class="btn btn-outline-secondary fileinput-exists"
                           data-dismiss="fileinput">Remove</a>
                    </div>
                </div>

                @if($errors->has('image'))
                    <span class="help-block">{{$errors->first('image')}}</span>
                @endif
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Tags</h3>
        </div>
        <div class="box-body">
            <div class="form-group">
                {!! Form::text('post_tags', null, ['class' => 'form-control']) !!}
            </div>
        </div>
    </div>
</div>

resources/views/backend/blog/index.blade.php
@extends('layouts.backend.main')
@section('title','MyBlog | Dashboar')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Blog
                <small>Display All Posts</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.blog.index')}}">Blog</a></li>
                <li class="active">All Posts</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <div class="pull-left">
                                <a class="btn btn-success" href="{{route('backend.blog.create')}}"><i
                                        class="fa fa-plus">Add New Post</i></a>
                            </div>
                            <div class="pull-right" style="padding:7px 0">
                                <?php $list = []; ?>
                                @foreach($statusList as $key=>$value)
                                    @if($value)
                                        <?php $selected = Request::get('status') == $key ? 'selected-status' : ''  ?>
                                        <?php $list[] = "<a class=\"{$selected}\" href=\"?status={$key}\">" . ucwords($key) . "({$value})" . "</a>"  ?>
                                    @endif
                                @endforeach
                                {!! implode(' | ',$list) !!}
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body ">
                            @include('includes.backend.message')
                            @if (!$posts->count())
                                <div class="alert alert-danger">
                                    <strong>No record found</strong>
                                </div>
                            @else
                                @if($onlyTrashed)
                                    @include('backend.blog.table-trash')
                                @else
                                    @include('backend.blog.table')
                                @endif
                            @endif
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer clearfix">
                            @if($onlyTrashed)
                                {{$posts->appends(request()->input())->links()}}
                            @else
                                {{$posts->links()}}
                            @endif
                            <div class="pull-right">
                                <small>{{$posts->total()}} {{str_plural('post',$posts->total())}}</small>
                            </div>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/blog/script.blade.php
@section('script')
    <script src="{{asset('/backend/js/moment-with-locales.js')}}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
    <script src="{{asset('/backend/plugins/tag-editor/jquery.caret.min.js')}}"></script>
    <script src="{{asset('/backend/plugins/tag-editor/jquery.tag-editor.min.js')}}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>
        var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        };
        CKEDITOR.replace('body', options);
        var option = {
            showClear: true,
            defaultDate: new Date(),
            format: 'Y-MM-DD HH:mm:ss'
        };
        jQuery(document).ready(function () {
            var tagOptions = {};
            tagOptions.autocomplete = {delay: 0, // show suggestions immediately
                position: { collision: 'flip' }, // automatic menu position up/down
                source: '/tags'};
            @if($post->exists)
                tagOptions.initialTags = {!! $post->tags_list !!};
            @endif
            $('input[name=post_tags]').tagEditor(tagOptions);

            $('#published_at').datetimepicker(option);
            $('#draft-btn').click(function (event) {
                event.preventDefault();
                $('#published_at').val("");
                $('#post-form').submit();
            });
        });

    </script>
@endsection