routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);
Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);
Route::post('/blog/{post}/comments', [
    'uses' => 'BlogController@comments',
    'as' => 'blog.comments'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);
Route::get('/author/{user}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);
Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit')->name('edit.account');
Route::put('/edit-account/', 'Backend\HomeController@update')->name('update.account');

Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('blog', 'BlogController');
    Route::post('blog/restore/{id}', [
        'uses' => 'BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('blog/force-destroy/{id}', [
        'uses' => 'BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
});
Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController', ['except' => 'destroy']);
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy'
    ]);
    Route::get('users/{user}', [
        'as' => 'users.confirm',
        'uses' => 'UserController@confirm'
    ]);
});

Route::get('/tags',function (){
    $tags = App\Tag::pluck('name');
    return $tags;
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','bio',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // Relationships
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    // Accessors- Mutators
    // Xử lý việc update user, nếu ko update password sẽ ko báo lỗi not null
    public function setPasswordAttribute($value)
    {
        if (!empty($value)) $this->attributes['password'] = bcrypt($value);
    }

    public function setBioAttribute($value)
    {
        if(!empty($value)){
            $this->attributes['bio'] = $value;
        } else {
            $this->attributes['bio'] = " ";
        }
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{

    protected $limit = 3;
    protected $uploadPath;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permission');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\CreatePostRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = config('cms.image.directory');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = false;
        if (($status = $request->get('status')) && $status == 'trash') {
            $posts = Post::onlyTrashed()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
            $onlyTrashed = true;
        } elseif (($status = $request->get('status')) && $status == 'published') {
            $posts = Post::published()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'scheduled') {
            $posts = Post::scheduled()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'draft') {
            $posts = Post::draft()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'own') {
            $posts = $request->user()->posts()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } else {
            $posts = Post::with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        }
        $statusList = $this->statusList($request);
        return view('backend.blog.index', compact('posts', 'onlyTrashed', 'statusList'));
    }

    private function statusList($request)
    {
        return [
            'own' => $request->user()->posts()->count(),
            'all' => Post::count(),
            'published' => Post::published()->count(),
            'scheduled' => Post::scheduled()->count(),
            'draft' => Post::draft()->count(),
            'trash' => Post::onlyTrashed()->count()
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.create', compact('post', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $data = $this->handleRequest($request);
        $newPost = $request->user()->posts()->create($data);
        if ($newPost) {
            $newPost->createTags($data["post_tags"]);
            Session::flash('success', 'Tạo mới thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Tạo mới thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    private function handleRequest($request)
    {
        $request->request->add(['view_count' => 0]);
        $data = $request->all();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $time = time();
            $fileName = $time . $fileName;
            $destination = $this->uploadPath;
            $successUploaded = $image->move($destination, $fileName);
            // Create thumb image
            if ($successUploaded) {
                $width = config('cms.image.thumbnail.width');
                $height = config('cms.image.thumbnail.height');
                $extension = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$extension}", "_thumb.{$extension}", $fileName);

                Image::make($destination . '/' . $fileName)
                    ->resize($width, $height)
                    ->save($destination . '/' . $thumbnail);
            }
            // end Create thumb image
            $data['image'] = $fileName;
        }
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreatePostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        $oldImage = $post->image;
        $data = $this->handleRequest($request);
        $updated = $post->update($data);

        if ($updated) {
            $post->createTags($data['post_tags']);
            if ($oldImage != $post->image) {
                $this->removeImage($oldImage);
            }
            Session::flash('success', 'Sửa thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Sửa thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id)->delete();
        if ($post) {
            return redirect()->back()->with('trash-message', ['Xóa post thành công', $id]);
        } else {
            return redirect()->back()->with('fail', 'Xóa post thất bại');
        }
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->find($id)->restore();
        if ($post) {
            return redirect()->back()->with('success', 'Undo post thành công');
        } else {
            return redirect()->back()->with('fail', 'Undo post thất bại');
        }
    }

    public function forceDestroy($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $image = $post->image;
        $deletePost = $post->forceDelete();

        if ($deletePost) {
            $this->removeImage($image);
            return redirect()->back()->with('success', 'Xóa thành công');
        } else {
            return redirect()->back()->with('fail', 'Xóa thất bại');
        }
    }

    public function removeImage($image)
    {
        if (!empty($image)) {
            $imagePath = $this->uploadPath . '/' . $image;
            $ext = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $image);
            $thumbnailPath = $this->uploadPath . '/' . $thumbnail;
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
            if (file_exists($thumbnailPath)) {
                unlink($thumbnailPath);
            }
        }
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CategoryController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        $categories = Category::orderBy('title')->with('posts')->paginate($this->limit);
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $newCategory = Category::create($request->all());
        if ($newCategory) {
            Session::flash('success', 'Tạo mới thành công');
            return redirect()->route('backend.categories.index');
        } else {
            Session::flash('fail', 'Tạo mới thất bại');
            return redirect()->route('backend.categories.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('backend.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->update($request->all());
        if ($category) {
            Session::flash('success', 'Sửa thành công');
            return redirect()->route('backend.categories.index');
        } else {
            Session::flash('fail', 'Sửa thất bại');
            return redirect()->route('backend.categories.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($id == config('cms.default_category_id')) {
            return redirect()->back()->with('success', 'Bạn không thể xóa category mặc định');
        }
        $category = Category::findOrFail($id);
        Post::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_id')]);
        $category->delete();
        if ($category) {
            return redirect()->back()->with('success', 'Xóa thành công');
        } else {
            return redirect()->back()->with('fail', 'Xóa thất bại');
        }
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AccountUpdateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('backend.home.index');
    }

    public function edit(Request $request)
    {
        $user = $request->user();
        return view('backend.home.edit',compact('user'));
    }

    public function update(AccountUpdateRequest $request)
    {
        $user = $request->user();
        $update = $user->update($request->all());
        if($update){
            return redirect()->back()->with('success','Account was updated successfully');
        } else {
            return redirect()->back()->with('fail','Account was updated fail');
        }
    }
}

resources/views/backend/users/confirm.blade.php
@extends('layouts.backend.main')
@section('title','MyUser | Dashboar')
@section('link')
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My User
                <small>Delete Confirm</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.users.index')}}">User</a></li>
                <li class="active">Delete confirm</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {!! Form::open([
                'method'=>'delete',
                'route'=>['backend.users.destroy',$user->id],
                'files'=>TRUE,
                'id'=>'user-form'
                ]) !!}
                <div class="col-xs-9">
                    <div class="box">
                        <div class="body">
                            <p>
                                You have specified this user for deletion:
                            </p>
                            <p>
                                ID #{{$user->id}} : {{$user->name}}
                            </p>
                            <p>
                                What should be done with content own by this user?
                            </p>
                            <p>
                                <input type="radio" name="delete_option" value="delete" checked>Delete All Content
                            </p>
                            <p>
                                <input type="radio" name="delete_option" value="attribute"> Attribute content to:
                                {{Form::select('selected_user',$users,null)}}
                            </p>
                        </div>
                        <div class="footer">
                            <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            <a href="{{route('backend.users.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/users/create.blade.php
@extends('layouts.backend.main')
@section('title','MyUser | Dashboar')
@section('link')
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My User
                <small>Add new user</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.users.index')}}">User</a></li>
                <li class="active">Add new user</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {!! Form::open([
                'method'=>'POST',
                'route'=>'backend.users.store',
                'files'=>TRUE,
                'id'=>'user-form'
                ]) !!}
                @include('backend.users.form')
                {!! Form::close() !!}
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/users/edit.blade.php
@extends('layouts.backend.main')
@section('title','MyBlog | Dashboar')
@section('link')
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Blog
                <small>Edit user</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.users.index')}}">User</a></li>
                <li class="active">Edit User</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                {!! Form::model($user,[
                'method'=>'PUT',
                'route'=>['backend.users.update',$user->id],
                'files'=>TRUE,
                'id'=>'user-form'
                ]) !!}
                @include('backend.users.form')
                {!! Form::close() !!}
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/users/form.blade.php
<div class="col-xs-9">
    <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                {!! Form::label('name') !!}
                {!! Form::text('name',null,['class'=>'form-control']) !!}
                @if($errors->has('name'))
                    <span class="help-block">{{$errors->first('name')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                {!! Form::label('email') !!}
                {!! Form::email('email',null,['class'=>'form-control']) !!}
                @if($errors->has('email'))
                    <span class="help-block">{{$errors->first('email')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                {!! Form::label('password') !!}
                {!! Form::password('password',['class'=>'form-control']) !!}
                @if($errors->has('password'))
                    <span class="help-block">{{$errors->first('password')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                {!! Form::label('password_confirmation') !!}
                {!! Form::password('password_confirmation',['class'=>'form-control']) !!}
                @if($errors->has('password_confirmation'))
                    <span class="help-block">{{$errors->first('password_confirmation')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('role') ? 'has-error' : '' }}">
                {!! Form::label('role') !!}
                <?php $defaultRole = !empty($user) ? $user->roles->first()->id : null; ?>
                @if(!empty($user) && ($user->id == config('cms.default_user_id')) || isset($hiddenRoleDropdown) )
                    {!! Form::hidden('role',$user->roles->first()->display_name) !!}
                    <p class="form-control-static">{{$user->roles->first()->display_name}}</p>
                @else
                    {!! Form::select('role',$roles,$defaultRole,['class'=>'form-control','placeholder'=>'Choose a role']) !!}
                @endif
                @if($errors->has('role'))
                    <span class="help-block">{{$errors->first('role')}}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('bio') ? 'has-error' : '' }}">
                {!! Form::label('bio') !!}
                {!! Form::textarea('bio',null,['class'=>'form-control']) !!}
                @if($errors->has('bio'))
                    <span class="help-block">{{$errors->first('bio')}}</span>
                @endif
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <button class="btn btn-primary">{{isset($user) ? "Update" : "Create"}}</button>
                <a class="btn btn-default" href="{{route('backend.users.index')}}">Quay lại</a>
            </div>
        </div>
    </div>
    <!-- /.box -->
</div>

resources/views/backend/users/index.blade.php
@extends('layouts.backend.main')
@section('title','MyUser | Dashboar')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Category
                <small>Display All Users</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Dashboard</a>
                </li>
                <li><a href="{{route('backend.users.index')}}">Users</a></li>
                <li class="active">All Users</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <div class="pull-left">
                                <a class="btn btn-success" href="{{route('backend.users.create')}}"><i
                                        class="fa fa-plus">Add New User</i></a>
                            </div>
                            <div class="pull-right">

                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body ">
                            @include('includes.backend.message')
                            @if (!$users->count())
                                <div class="alert alert-danger">
                                    <strong>No record found</strong>
                                </div>
                            @else
                                @include('backend.users.table')
                            @endif
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer clearfix">
                                {{$users->appends(request()->input())->links()}}
                            <div class="pull-right">
                                <small>{{$users->total()}} {{str_plural('user',$users->total())}}</small>
                            </div>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/users/table.blade.php
<table class="table table-bordered">
    <thread>
        <tr>
            <td width="80">Action</td>
            <td>Name</td>
            <td>Email</td>
            <td>Role</td>
        </tr>
    </thread>
    <tbody>
    <?php $currentUser = auth()->user(); ?>
    @foreach($users as $user)
        <tr>
            <td>
                <a href="{{route('backend.users.edit',$user->id)}}"
                   class="btn btn-xs btn-default">
                    <i class="fa fa-edit"></i>
                </a>
                @if($user->id == config('cms.default_user_id') || $user->id == $currentUser->id )
                    <button onclick="return false" type="submit" class="btn btn-xs btn-danger disabled">
                        <i class="fa fa-times"></i>
                    </button>
                @else
                    <a href="{{route('backend.users.confirm',$user->id)}}"
                       class="btn btn-xs btn-danger">
                        <i class="fa fa-times"></i>
                    </a>
                @endif
            </td>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>{{$user->roles->first()->display_name}}</td>
        </tr>
    @endforeach
    </tbody>
</table>