routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);
Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);
Route::post('/blog/{post}/comments', [
    'uses' => 'BlogController@comments',
    'as' => 'blog.comments'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);
Route::get('/author/{user}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);
Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit')->name('edit.account');
Route::put('/edit-account/', 'Backend\HomeController@update')->name('update.account');

Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('blog', 'BlogController');
    Route::post('blog/restore/{id}', [
        'uses' => 'BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('blog/force-destroy/{id}', [
        'uses' => 'BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
});
Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController', ['except' => 'destroy']);
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy'
    ]);
    Route::get('users/{user}', [
        'as' => 'users.confirm',
        'uses' => 'UserController@confirm'
    ]);
});

Route::get('/tags',function (){
    $tags = App\Tag::pluck('name');
    return $tags;
});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use function GuzzleHttp\Psr7\str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'view_count', 'image'];
    protected $dates = ['published_at', 'created_at', 'updated_at'];
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];

        foreach ($tags as $tag) {
            $newTag = Tag::firstOrCreate(
                ['slug' => str_slug($tag), 'name' => ucwords(trim($tag))]
            );
            $newTag->save();

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }

    // Relationships
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    // Accessors- Mutators
    public function getImageUrlAttribute($image)
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $this->image;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $this->image);
            }
        }
        return $imageUrl;
    }

    public function getDateAttribute()
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getImageThumbUrlAttribute()
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            // lấy extension = cách tìm dấu . cuối cùng trong tên image và lấy từ sau dấu chấm đến hết
            $extenstion = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".$extenstion", "_thumb.$extenstion", $this->image);
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $thumbnail;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $thumbnail);
            }
        }
        return $imageUrl;
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function getTagsHtmlAttribute()
    {
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = '<a href="' . route('tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(', ', $anchors);
    }

    public function commentsNumber()
    {
        $commentsNumber = $this->comments->count();
        return $commentsNumber . ' ' . str_plural('Comment', $commentsNumber);
    }

    public function setPublishedAtAttribute($value)
    {
        if ($value) {
            $value = date("Y-m-d H:i:s", strtotime($value));
        }
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if ($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel()
    {
        if (!$this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    // Scope
    public function scopeMoiNhat($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where("published_at", "<=", Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    // Get list Tháng - Năm - Số lượng Post
    public static function archives()
    {
        return static::selectRaw('count(id) post_count, YEAR(published_at) year, MONTHNAME(published_at) month')->published()->groupBy('year', 'month')->orderBy('published_at', 'desc')->get();
    }

    // check if user searched
    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }
        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereYear('published_at', $year);
        }

        if (isset($filter['term']) && $term = $filter['term']) {
            $query->where(function ($q) use ($term) {
                $q->whereHas('user', function ($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function ($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\CreatePostRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = config('cms.image.directory');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = false;
        if (($status = $request->get('status')) && $status == 'trash') {
            $posts = Post::onlyTrashed()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
            $onlyTrashed = true;
        } elseif (($status = $request->get('status')) && $status == 'published') {
            $posts = Post::published()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'scheduled') {
            $posts = Post::scheduled()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'draft') {
            $posts = Post::draft()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } elseif (($status = $request->get('status')) && $status == 'own') {
            $posts = $request->user()->posts()->with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        } else {
            $posts = Post::with('user', 'category')
                ->latest()
                ->paginate($this->limit);
        }
        $statusList = $this->statusList($request);
        return view('backend.blog.index', compact('posts', 'onlyTrashed', 'statusList'));
    }

    private function statusList($request)
    {
        return [
            'own' => $request->user()->posts()->count(),
            'all' => Post::count(),
            'published' => Post::published()->count(),
            'scheduled' => Post::scheduled()->count(),
            'draft' => Post::draft()->count(),
            'trash' => Post::onlyTrashed()->count()
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.create', compact('post', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $data = $this->handleRequest($request);
        $newPost = $request->user()->posts()->create($data);
        if ($newPost) {
            $newPost->createTags($data["post_tags"]);
            Session::flash('success', 'Tạo mới thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Tạo mới thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    private function handleRequest($request)
    {
        $request->request->add(['view_count' => 0]);
        $data = $request->all();
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $time = time();
            $fileName = $time . $fileName;
            $destination = $this->uploadPath;
            $successUploaded = $image->move($destination, $fileName);
            // Create thumb image
            if ($successUploaded) {
                $width = config('cms.image.thumbnail.width');
                $height = config('cms.image.thumbnail.height');
                $extension = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$extension}", "_thumb.{$extension}", $fileName);

                Image::make($destination . '/' . $fileName)
                    ->resize($width, $height)
                    ->save($destination . '/' . $thumbnail);
            }
            // end Create thumb image
            $data['image'] = $fileName;
        }
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categories = Category::pluck('title', 'id');
        return view('backend.blog.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreatePostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        $oldImage = $post->image;
        $data = $this->handleRequest($request);
        $updated = $post->update($data);

        if ($updated) {
            $post->createTags($data['post_tags']);
            if ($oldImage != $post->image) {
                $this->removeImage($oldImage);
            }
            Session::flash('success', 'Sửa thành công');
            return redirect()->route('backend.blog.index');
        } else {
            Session::flash('fail', 'Sửa thất bại');
            return redirect()->route('backend.blog.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id)->delete();
        if ($post) {
            return redirect()->back()->with('trash-message', ['Xóa post thành công', $id]);
        } else {
            return redirect()->back()->with('fail', 'Xóa post thất bại');
        }
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->find($id)->restore();
        if ($post) {
            return redirect()->back()->with('success', 'Undo post thành công');
        } else {
            return redirect()->back()->with('fail', 'Undo post thất bại');
        }
    }

    public function forceDestroy($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $image = $post->image;
        $deletePost = $post->forceDelete();

        if ($deletePost) {
            $this->removeImage($image);
            return redirect()->back()->with('success', 'Xóa thành công');
        } else {
            return redirect()->back()->with('fail', 'Xóa thất bại');
        }
    }

    public function removeImage($image)
    {
        if (!empty($image)) {
            $imagePath = $this->uploadPath . '/' . $image;
            $ext = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $image);
            $thumbnailPath = $this->uploadPath . '/' . $thumbnail;
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
            if (file_exists($thumbnailPath)) {
                unlink($thumbnailPath);
            }
        }
    }
}

resources/views/blog/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @if ( !$posts->count() )
                    <div class="alert alert-warning">
                        <p>Nothing found</p>
                    </div>
                @else
                    @include('includes.alert')

                    @foreach($posts as $key=>$post)
                        <article class="post-item">
                            @if ( $post->image )
                                <div class="post-item-image">
                                    <a href="{{route('blog.show',$post->slug)}}">
                                        <img src="{{$post->image_url}}" alt="">
                                    </a>
                                </div>
                            @endif
                            <div class="post-item-body">
                                <div class="padding-10">
                                    <h2><a href="{{route('blog.show',$post->slug)}}">{{$post->title}}</a></h2>
                                    <p>{{$post->excerpt}}</p>
                                </div>

                                <div class="post-meta padding-10 clearfix">
                                    <div class="pull-left">
                                        <ul class="post-meta-group">
                                            <li><i class="fa fa-user"></i><a
                                                    href="{{route('author',$post->user->slug)}}">{{$post->user->name}}</a>
                                            </li>
                                            <li><i class="fa fa-clock-o"></i>
                                                <time>{{$post->date}}</time>
                                            </li>
                                            <li><i class="fa fa-folder"></i><a
                                                    href="{{route('category',$post->category->slug)}}"> {{$post->category->title}}</a>
                                            </li>
                                            <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                            <li><i class="fa fa-comments"></i><a
                                                    href="{{route('blog.show',$post->slug)}}#comment-label">{{$post->commentsNumber()}}</a></li>
                                        </ul>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{route('blog.show',$post->slug)}}">Continue Reading &raquo;</a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    @endforeach
                @endif
                <nav>
                    {{$posts->appends(request()->only(['term','month','year']))->links()}}
                </nav>
            </div>
            @include('includes.sidebar')
        </div>
    </div>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <article class="post-item post-detail">
                    @if( $post->image_url )
                        <div class="post-item-image">
                            <a href="#">
                                <img src="{{ $post->image_url }}" alt="{{ $post->title }}">
                            </a>
                        </div>
                    @endif
                    <div class="post-item-body">
                        <div class="padding-10">
                            <h1>{{ $post->title }}</h1>

                            <div class="post-meta no-border">
                                <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><a
                                            href="{{route('author',$post->user->slug)}}">{{$post->user->name}}</a></li>
                                    <li><i class="fa fa-clock-o"></i>
                                        <time>{{ $post->date }}</time>
                                    </li>
                                    <li><i class="fa fa-folder"></i><a
                                            href="{{route('category',$post->category->slug)}}"> {{$post->category->title}}</a>
                                    </li>
                                    <li><i class="fa fa-tag"></i><a href="#">{!! $post->tags_html !!}</a></li>
                                    <li><i class="fa fa-comments"></i><a href="#comment-label">{{$post->commentsNumber()}}</a></li>
                                </ul>
                            </div>
                            {!! $post->body !!}
                        </div>
                    </div>
                </article>

                <article class="post-author padding-10">
                    <div class="media">
                        <div class="media-left">
                            <a href="{{route('author',$post->user->slug)}}">
                                <img alt="{{$post->user->name}}" src="{{asset('img/author.jpg')}}" class="media-object">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><a
                                    href="{{route('author',$post->user->slug)}}">{{$post->user->name}}</a></h4>
                            <div class="post-author-count">
                                <a href="{{route('author',$post->user->slug)}}">
                                    <i class="fa fa-clone"></i>
                                    <?php $postCount = $post->user->posts()->published()->count() ?>
                                    {{$postCount}} {{str_plural('post',$postCount)}}
                                </a>
                            </div>
                            <p>{{$post->user->bio}}</p>
                        </div>
                    </div>
                </article>
                @include('includes.comments')
            </div>
            @include('includes.sidebar')
        </div>
    </div>
@endsection