routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);
Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);
Route::post('/blog/{post}/comments', [
    'uses' => 'BlogController@comments',
    'as' => 'blog.comments'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);
Route::get('/author/{user}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);
Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit')->name('edit.account');
Route::put('/edit-account/', 'Backend\HomeController@update')->name('update.account');

Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('blog', 'BlogController');
    Route::post('blog/restore/{id}', [
        'uses' => 'BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('blog/force-destroy/{id}', [
        'uses' => 'BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
});
Route::namespace('Backend')->prefix('backend')->name('backend.')->group(function () {
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController', ['except' => 'destroy']);
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy'
    ]);
    Route::get('users/{user}', [
        'as' => 'users.confirm',
        'uses' => 'UserController@confirm'
    ]);
});

Route::get('/tags',function (){
    $tags = App\Tag::pluck('name');
    return $tags;
});

app/Comment.php
<?php

namespace App;

use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['user_name', 'user_email', 'user_url', 'body', 'post_id'];

    //Relationships
    public function posts()
    {
        return $this->belongsTo(Post::class);
    }

    // Accessors- Mutators
    public function getDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getBodyHtmlAttribute()
    {
        return Markdown::convertToHtml(e($this->body));
    }
}

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use function GuzzleHttp\Psr7\str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'view_count', 'image'];
    protected $dates = ['published_at', 'created_at', 'updated_at'];
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];

        foreach ($tags as $tag) {
            $newTag = Tag::firstOrCreate(
                ['slug' => str_slug($tag), 'name' => ucwords(trim($tag))]
            );
            $newTag->save();

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }

    // Relationships
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    // Accessors- Mutators
    public function getImageUrlAttribute($image)
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $this->image;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $this->image);
            }
        }
        return $imageUrl;
    }

    public function getDateAttribute()
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getImageThumbUrlAttribute()
    {
        $imageUrl = "";
        if (!is_null($this->image)) {
            // lấy extension = cách tìm dấu . cuối cùng trong tên image và lấy từ sau dấu chấm đến hết
            $extenstion = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".$extenstion", "_thumb.$extenstion", $this->image);
            $dicrectory = config('cms.image.directory');
            $imagePath = public_path() . "/{$dicrectory}/" . $thumbnail;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/{$dicrectory}/" . $thumbnail);
            }
        }
        return $imageUrl;
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function getTagsHtmlAttribute()
    {
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = '<a href="' . route('tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(', ', $anchors);
    }

    public function commentsNumber()
    {
        $commentsNumber = $this->comments->count();
        return $commentsNumber . ' ' . str_plural('Comment', $commentsNumber);
    }

    public function setPublishedAtAttribute($value)
    {
        if ($value) {
            $value = date("Y-m-d H:i:s", strtotime($value));
        }
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if ($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel()
    {
        if (!$this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    // Scope
    public function scopeMoiNhat($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where("published_at", "<=", Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    // Get list Tháng - Năm - Số lượng Post
    public static function archives()
    {
        return static::selectRaw('count(id) post_count, YEAR(published_at) year, MONTHNAME(published_at) month')->published()->groupBy('year', 'month')->orderBy('published_at', 'desc')->get();
    }

    // check if user searched
    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }
        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereYear('published_at', $year);
        }

        if (isset($filter['term']) && $term = $filter['term']) {
            $query->where(function ($q) use ($term) {
                $q->whereHas('user', function ($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function ($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }
}

resources/views/includes/alert.blade.php
@if ( isset($categoryName) )
    <div class="alert alert-info">
        <p>Category: <strong>{{$categoryName}}</strong></p>
    </div>
@endif
@if ( isset($authorName) )
    <div class="alert alert-info">
        <p>Author: <strong>{{$authorName}}</strong></p>
    </div>
@endif
@if ( isset($tagName) )
    <div class="alert alert-info">
        <p>Tag: <strong>{{$tagName}}</strong></p>
    </div>
@endif
@if ( $term = request('term') )
    <div class="alert alert-info">
        <p>Search Results for: <strong>{{$term}}</strong></p>
    </div>
@endif
@if(session('success'))
    <div class="alert alert-info">
        {{session('success')}}
    </div>
@endif
@if(session('fail'))
    <div class="alert alert-danger">
        {{session('fail')}}
    </div>
@endif

resources/views/includes/comments.blade.php
<article class="post-comments" id="comment-label">
    <h3><i class="fa fa-comments"></i> {{$post->commentsNumber() }}</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            @foreach($postComments as $comment)
                <li class="comment-item">
                    <div class="comment-heading clearfix">
                        <div class="comment-author-meta">
                            <h4>{{$comment->user_name}}
                                <small>{{$comment->date}}</small>
                            </h4>
                        </div>
                    </div>
                    <div class="comment-content">
                        {!! $comment->body_html !!}
                    </div>
                </li>
            @endforeach
            {{--<li class="comment-item">--}}
            {{--<div class="comment-heading clearfix">--}}
            {{--<div class="comment-author-meta">--}}
            {{--<h4>John Doe--}}
            {{--<small>January 14, 2016</small>--}}
            {{--</h4>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<div class="comment-content">--}}
            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione--}}
            {{--nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis--}}
            {{--assumenda magnam doloribus!</p>--}}
            {{--<p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae--}}
            {{--inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias--}}
            {{--aliquid quibusdam tempore. Vel.</p>--}}

            {{--<ul class="comments-list-children">--}}
            {{--<li class="comment-item">--}}
            {{--<div class="comment-heading clearfix">--}}
            {{--<div class="comment-author-meta">--}}
            {{--<h4>John Doe--}}
            {{--<small>January 14, 2016</small>--}}
            {{--</h4>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<div class="comment-content">--}}
            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est,--}}
            {{--atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam--}}
            {{--ipsam perspiciatis assumenda magnam doloribus!</p>--}}
            {{--<p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis--}}
            {{--enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit--}}
            {{--explicabo, non molestias aliquid quibusdam tempore. Vel.</p>--}}
            {{--</div>--}}
            {{--</li>--}}

            {{--<li class="comment-item">--}}
            {{--<div class="comment-heading clearfix">--}}
            {{--<div class="comment-author-meta">--}}
            {{--<h4>John Doe--}}
            {{--<small>January 14, 2016</small>--}}
            {{--</h4>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<div class="comment-content">--}}
            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est,--}}
            {{--atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam--}}
            {{--ipsam perspiciatis assumenda magnam doloribus!</p>--}}
            {{--<p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis--}}
            {{--enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit--}}
            {{--explicabo, non molestias aliquid quibusdam tempore. Vel.</p>--}}

            {{--<ul class="comments-list-children">--}}
            {{--<li class="comment-item">--}}
            {{--<div class="comment-heading clearfix">--}}
            {{--<div class="comment-author-meta">--}}
            {{--<h4>John Doe--}}
            {{--<small>January 14, 2016</small>--}}
            {{--</h4>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<div class="comment-content">--}}
            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt--}}
            {{--nulla est, atque ratione nostrum cumque ducimus maxime, amet enim--}}
            {{--tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam--}}
            {{--doloribus!</p>--}}
            {{--<p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab--}}
            {{--non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci--}}
            {{--nostrum reprehenderit explicabo, non molestias aliquid quibusdam--}}
            {{--tempore. Vel.</p>--}}
            {{--</div>--}}
            {{--</li>--}}
            {{--</ul>--}}
            {{--</div>--}}
            {{--</li>--}}
            {{--</ul>--}}
            {{--</div>--}}
            {{--</li>--}}
        </ul>
        <nav>
            {!! $postComments->links() !!}
        </nav>

    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        @include('includes.alert')
        {!! Form::open([
        'route'=>['blog.comments',$post->slug],
        'method'=>'POST'
            ]) !!}
        <div class="form-group required {{ $errors->has('user_name') ? 'has-error' : '' }}">
            <label for="name">Name</label>
            {!! Form::text('user_name',null,['class'=>'form-control']) !!}
            @if($errors->has('user_name'))
                <span class="help-block">{{$errors->first('user_name')}}</span>
            @endif
        </div>
        <div class="form-group required {{ $errors->has('user_email') ? 'has-error' : '' }}">
            <label for="email">Email</label>
            {!! Form::text('user_email',null,['class'=>'form-control']) !!}
            @if($errors->has('user_email'))
                <span class="help-block">{{$errors->first('user_email')}}</span>
            @endif
        </div>
        <div class="form-group">
            <label for="website">Website</label>
            {!! Form::text('user_url',null,['class'=>'form-control']) !!}
        </div>
        <div class="form-group required {{ $errors->has('body') ? 'has-error' : '' }}">
            <label for="comment">Comment</label>
            {!! Form::textarea('body',null,['rows'=>6,'class'=>'form-control']) !!}
            @if($errors->has('body'))
                <span class="help-block">{{$errors->first('body')}}</span>
            @endif
        </div>
        <div class="clearfix">
            <div class="pull-left">
                <button type="submit" class="btn btn-lg btn-success">Submit</button>
            </div>
            <div class="pull-right">
                <p class="text-muted">
                    <span class="required">*</span>
                    <em>Indicates required fields</em>
                </p>
            </div>
        </div>
        {!! Form::close() !!}
    </div>

</article>

resources/views/includes/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="copyright">&copy; 2016 Edo Masaru</p>
            </div>
            <div class="col-md-4">
                <nav>
                    <ul class="social-icons">
                        <li><a href="#" class="i fa fa-facebook"></a></li>
                        <li><a href="#" class="i fa fa-twitter"></a></li>
                        <li><a href="#" class="i fa fa-google-plus"></a></li>
                        <li><a href="#" class="i fa fa-github"></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</footer>
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
</body>
</html>

resources/views/includes/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyBlog | My Awesome Blog</title>

    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">
</head>
<body>
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#the-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url('/')}}">MyBlog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="the-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="{{ route('blog') }}">Blog</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
</header>

resources/views/includes/sidebar.blade.php
<div class="col-md-4">
    <aside class="right-sidebar">
        <div class="search-widget">
            <form action="">
                <div class="input-group">
                    <input type="text" name="term" value="{{request('term')}}" class="form-control input-lg"
                           placeholder="Search for...">
                    <span class="input-group-btn">
                                <button class="btn btn-lg btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                    </span>
                </div>
            </form>
        </div>

        <div class="widget">
            <div class="widget-heading" id="category-heading">
                <h4>Categories</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                    @foreach($categories as $key=>$category)
                        <li>
                            <a href="{{route('category',$category->slug)}}"><i
                                    class="fa fa-angle-right"></i>{{$category->title}}</a>
                            <span class="badge pull-right">{{$category->posts->count()}}</span>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget">
            <div class="widget-heading" id="popular-heading">
                <h4>Popular Posts</h4>
            </div>
            <div class="widget-body">
                <ul class="popular-posts">
                    @foreach($popularPosts as $post)
                        <li>
                            @if ($post->image_thumb_url)
                                <div class="post-image">
                                    <a href="{{route('blog.show',$post->slug)}}">
                                        <img src="{{$post->image_thumb_url}}"/>
                                    </a>
                                </div>
                            @endif
                            <div class="post-body">
                                <h6><a href="{{route('blog.show',$post->slug)}}">{{$post->title}}</a></h6>
                                <div class="post-meta">
                                    <span>{{$post->date}}</span>
                                </div>
                            </div>
                        </li>
                    @endforeach

                </ul>
            </div>
        </div>

        <div class="widget" >
            <div class="widget-heading" id="tag-heading">
                <h4>Tags</h4>
            </div>
            <div class="widget-body">
                <ul class="tags">
                    @foreach($tags as $key=>$tag)
                        <li><a href="{{route('tag',$tag->slug)}}">{{$tag->name}}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget">
            <div class="widget-heading" id="archives-heading">
                <h4>Archives</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                    @foreach($archives as $archive)
                        <li>
                            <a href="{{route('blog',['month'=>$archive->month,'year'=>$archive->year])}}">{{$archive->month}} {{$archive->year}}</a>
                            <span class="badge pull-right">{{$archive->post_count}}</span>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </aside>
</div>